### ISSUE TITLE
Testing Script  failure

### ISSUE THREAD

**Issue by ageroul** [tyiannak/deep_audio_features#16]
Hello,
After a successful run of the **training script**, I got a model and applied it to the **testing script**. This is what I got after the execution:

`Traceback (most recent call last):
  File "basic_test.py", line 94, in <module>
    test_model(modelpath=model, ifile=ifile, layers_dropped=layers_dropped)
  File "basic_test.py", line 54, in test_model
    fuse=fuse)
TypeError: __init__() got an unexpected keyword argument 'spec_size'`

Thanks,

**Comment by DimitrisKatsiros** [comment]
@lobracost  
in https://github.com/tyiannak/deep_audio_features/commit/6488085486cd8d05ea380c66b56b6ef325826f71  inconsistent arguments were added in `class FeatureExtractorDataset(Dataset)`. `spec_size` is not keyword argument but given in basic_test.py . Should we just **add** this keyword argument or it there any **use** in `FeatureExtractorDataset` ?
https://github.com/tyiannak/deep_audio_features/blob/0ed7b4ff05a3c793792b34e573214663f54621d0/dataloading/dataloading.py#L11-L17
https://github.com/tyiannak/deep_audio_features/blob/0ed7b4ff05a3c793792b34e573214663f54621d0/bin/basic_test.py#L53

**Comment by lobracost** [comment]
> @ageroul thank you very much for the comment
> @lobracost
> in [6488085](https://github.com/tyiannak/deep_audio_features/commit/6488085486cd8d05ea380c66b56b6ef325826f71) inconsistent arguments were added in `class FeatureExtractorDataset(Dataset)`. `spec_size` is not keyword argument but given in basic_test.py . Should we just **add** this keyword argument or it there any **use** in `FeatureExtractorDataset` ?
> 
> https://github.com/tyiannak/deep_audio_features/blob/0ed7b4ff05a3c793792b34e573214663f54621d0/dataloading/dataloading.py#L11-L17
> 
> https://github.com/tyiannak/deep_audio_features/blob/0ed7b4ff05a3c793792b34e573214663f54621d0/bin/basic_test.py#L53

@DimitrisKatsiros  In order to handle audio files of different lengths we introduced the resizing technique. Specifically, when a model is getting trained, the average size of the dataset's spectrograms is calculated. This size is then saved to the models' parameters as spec_size. So it is not given in the dataset arguments, but it is calculated dynamically in the following lines https://github.com/tyiannak/deep_audio_features/blob/0ed7b4ff05a3c793792b34e573214663f54621d0/dataloading/dataloading.py#L75-L77

In case a user wants a fixed spectroctram size, this is possible by using the forced_size parameter. This is the case in a testing script where the user wants to apply the spec_size that the model is trained on. So @DimitrisKatsiros you are right. At the following line https://github.com/tyiannak/deep_audio_features/blob/0ed7b4ff05a3c793792b34e573214663f54621d0/bin/basic_test.py#L53

the right expressions is forced_size=spec_size.

I think this solves @ageroul  problem. I will try to commit the change and let you know in order to test it.

**Comment by lobracost** [comment]
I just commited the change with the following commit https://github.com/tyiannak/deep_audio_features/commit/210441e3a335cb90b2db0fcb57017880cf48d3d5

However, I cannot test it at the time. @ageroul please pull the changes and let us know if this solved your problem.

**Comment by ageroul** [comment]
> I just commited the change with the following commit [210441e](https://github.com/tyiannak/deep_audio_features/commit/210441e3a335cb90b2db0fcb57017880cf48d3d5)
> 
> However, I cannot test it at the time. @ageroul please pull the changes from the master branch and let us know if this solved your problem.

Yes! It's working now. Thanks @lobracost !
![Στιγμιότυπο 2021-01-11, 5 28 22 μμ](https://user-images.githubusercontent.com/77274063/104201685-b19ebb80-5432-11eb-9ffc-06172fa9ed9b.png)

** Is there an easy way to show the name of the class instead of the number?**

**Comment by lobracost** [comment]
> > I just commited the change with the following commit [210441e](https://github.com/tyiannak/deep_audio_features/commit/210441e3a335cb90b2db0fcb57017880cf48d3d5)
> > However, I cannot test it at the time. @ageroul please pull the changes from the master branch and let us know if this solved your problem.
> 
> Yes! It's working now. Thanks @lobracost !
> ![Στιγμιότυπο 2021-01-11, 5 28 22 μμ](https://user-images.githubusercontent.com/77274063/104201685-b19ebb80-5432-11eb-9ffc-06172fa9ed9b.png)
> 
> ** Is there an easy way to show the name of the class instead of the number?**

@ageroul We do not have a function that maps the classes of a problem to their real names. You can do that for your own dataset by creating a script.
